### ISSUE TITLE
Mockup do Projeto no Figma

### ISSUE THREAD

**Issue by Heber-Wl** [Heber-Wl/Investir#1]
Nesse etapa, será feito a construção do mockup do projeto no Figma, para que os desenvolvedores front-end comecem a trabalhar os mais rápido o possível dentro da sprint.

**Comment by Heber-Wl** [comment]
Nesse etapa, será feito a construção do mockup do projeto no Figma, para que os desenvolvedores front-end comecem a trabalhar os mais rápido o possível dentro da sprint.

**Comment by Heber-Wl** [comment]
![Image](https://github.com/user-attachments/assets/bcf1c8b0-3a64-4798-acee-356607f82d7a)

**Comment by GuiAlbg** [comment]
![image](https://github.com/user-attachments/assets/91178ded-2376-4136-952b-f0570a56e6c2)
![image](https://github.com/user-attachments/assets/9252c582-73fe-4cbb-a6c9-3e8cbb24d976)
![image](https://github.com/user-attachments/assets/db3b5a73-ebf3-40fd-aa24-b4563f08cf58)
